#!/usr/bin/env bash
# This script is displaying "Best School" 10 times,4 is badluck 8 is goodluck
i=0
while ((i < 10))
do 
	((i++))
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
	echo "Best School"
	fi
done

